version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/API
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: solohiddin
      POSTGRES_HOST: db 
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
