# Generated by Django 5.2.7 on 2025-10-02 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('soni', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mijoz')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xodim')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mijoz')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.xodim')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zakaz')),
            ],
        ),
    ]
