# Generated by Django 5.2.7 on 2025-10-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaz',
            name='tovar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tovar'),
        ),
    ]
