# Generated by Django 5.2.7 on 2025-10-02 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_zakaz_tovar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='tovar',
        ),
        migrations.CreateModel(
            name='ZakazItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tovar')),
                ('zakaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.mijoz')),
            ],
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
