# Generated by Django 5.2.7 on 2025-10-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_zakaz_tovar_zakazitem_delete_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakazitem',
            name='zakaz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.zakaz'),
        ),
    ]
